AllCops:
  TargetRubyVersion: 3.3.6
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 6

Style/ClassVars:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 20

Metrics/ParameterLists:
  Max: 8

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

plugins:
  - rubocop-rspec
  - rubocop-rake
